---
deployment:
  tasks:
    - export DEPLOYPATH=/home/ediamyid/aplikasi-nextjs
    - export NODE_ENV=development
    - export PATH=$DEPLOYPATH/node_modules/.bin:/opt/cpanel/ea-nodejs22/bin:/opt/cpanel/ea-nodejs20/bin:$PATH
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R * $DEPLOYPATH
    - cd $DEPLOYPATH && npm install --include=dev --no-save --no-engine --loglevel=error
    - cd $DEPLOYPATH && npx prisma generate
    - cd $DEPLOYPATH && npm run build
    - cd $DEPLOYPATH && mkdir -p .next/standalone/.next/static .next/standalone/public
    - cd $DEPLOYPATH && cp -rf public/* .next/standalone/public/
    - cd $DEPLOYPATH && cp -rf .next/static/* .next/standalone/.next/static/
    - cd $DEPLOYPATH && cp -rf .next/standalone/* .
    - cd $DEPLOYPATH && cp server.js app.js
    - cd $DEPLOYPATH && mkdir -p tmp && touch tmp/restart.txt